import { useState } from 'react';
import { Sparkles, Code } from 'lucide-react';

function SimplifiedApp() {
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [aiPrompt, setAiPrompt] = useState('');
    const [generatedCode, setGeneratedCode] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const handleLogin = (e: React.FormEvent) => {
        e.preventDefault();
        if (email && password) {
            setIsLoggedIn(true);
        }
    };

    const handleGenerateCode = async () => {
        if (!aiPrompt) return;

        setIsGenerating(true);
        // Simulate AI code generation
        await new Promise(r => setTimeout(r, 2000));

        // Mock generated code based on prompt
        const mockCode = `// Generated from: "${aiPrompt}"
function ${aiPrompt.toLowerCase().replace(/\s+/g, '_')}() {
  // AI-generated implementation
  console.log("This code was generated by AI!");
  
  return {
    success: true,
    message: "Code generated successfully"
  };
}

export default ${aiPrompt.toLowerCase().replace(/\s+/g, '_')};`;

        setGeneratedCode(mockCode);
        setIsGenerating(false);
    };

    // Landing Page (Not Logged In)
    if (!isLoggedIn) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-black via-blue-900 to-purple-900 text-white">
                <div className="container mx-auto px-4 py-16">
                    {/* Hero Section */}
                    <div className="text-center mb-16">
                        <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-gradient-to-br from-blue-500 to-purple-500 mb-8">
                            <Sparkles size={48} />
                        </div>
                        <h1 className="text-6xl font-bold mb-6">
                            AI Code Generator
                        </h1>
                        <p className="text-2xl text-gray-300 mb-12">
                            Type what you want. AI writes the code.
                        </p>
                    </div>

                    {/* Login Form */}
                    <div className="max-w-md mx-auto bg-white/10 backdrop-blur-xl rounded-2xl p-8 border border-white/20">
                        <h2 className="text-2xl font-bold mb-6 text-center">Sign In to Start</h2>
                        <form onSubmit={handleLogin} className="space-y-4">
                            <input
                                type="email"
                                placeholder="Email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                className="w-full px-4 py-3 bg-black/50 border border-white/20 rounded-lg focus:border-blue-500 focus:outline-none"
                                required
                            />
                            <input
                                type="password"
                                placeholder="Password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                className="w-full px-4 py-3 bg-black/50 border border-white/20 rounded-lg focus:border-blue-500 focus:outline-none"
                                required
                            />
                            <button
                                type="submit"
                                className="w-full py-3 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 rounded-lg font-bold text-lg shadow-lg transition-all"
                            >
                                Start Coding with AI
                            </button>
                        </form>
                        <p className="text-center text-sm text-gray-400 mt-4">
                            Use: pranu21m@gmail.com for full access
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    // AI Code Generator (Logged In)
    return (
        <div className="min-h-screen bg-black text-white flex">
            {/* Left: AI Chat */}
            <div className="w-1/2 border-r border-white/10 flex flex-col">
                <div className="p-6 border-b border-white/10">
                    <h2 className="text-2xl font-bold flex items-center gap-2">
                        <Sparkles className="text-blue-400" />
                        AI Code Generator
                    </h2>
                    <p className="text-gray-400 text-sm mt-1">Logged in as: {email}</p>
                </div>

                <div className="flex-1 p-6">
                    <div className="mb-6">
                        <label className="block text-sm text-gray-400 mb-2">
                            What do you want to build?
                        </label>
                        <textarea
                            value={aiPrompt}
                            onChange={(e) => setAiPrompt(e.target.value)}
                            placeholder="Example: Create a login form with validation"
                            className="w-full h-32 px-4 py-3 bg-white/5 border border-white/10 rounded-lg focus:border-blue-500 focus:outline-none resize-none"
                        />
                    </div>

                    <button
                        onClick={handleGenerateCode}
                        disabled={isGenerating || !aiPrompt}
                        className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg font-bold text-lg shadow-lg transition-all flex items-center justify-center gap-2"
                    >
                        {isGenerating ? (
                            <>
                                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                                Generating...
                            </>
                        ) : (
                            <>
                                <Sparkles size={20} />
                                Generate Code
                            </>
                        )}
                    </button>
                </div>
            </div>

            {/* Right: Generated Code */}
            <div className="w-1/2 flex flex-col">
                <div className="p-6 border-b border-white/10 flex items-center justify-between">
                    <h2 className="text-2xl font-bold flex items-center gap-2">
                        <Code className="text-green-400" />
                        Generated Code
                    </h2>
                    {generatedCode && (
                        <button
                            onClick={() => navigator.clipboard.writeText(generatedCode)}
                            className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm transition-colors"
                        >
                            Copy Code
                        </button>
                    )}
                </div>

                <div className="flex-1 p-6 overflow-auto">
                    {generatedCode ? (
                        <pre className="bg-white/5 border border-white/10 rounded-lg p-4 text-sm font-mono overflow-x-auto">
                            <code className="text-green-400">{generatedCode}</code>
                        </pre>
                    ) : (
                        <div className="h-full flex items-center justify-center text-gray-500">
                            <div className="text-center">
                                <Code size={64} className="mx-auto mb-4 opacity-20" />
                                <p>Your generated code will appear here</p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

export default SimplifiedApp;
